(function(g){var window=this;var rAa=function(a,b,c,d){var e=b.Yb();g.T(a.element,"ytp-suggestion-set",!!e.videoId);var f=b.getPlaylistId();d=b.bd(c,d?d:"mqdefault.jpg");var k=b instanceof g.rO?g.WV(b.lengthSeconds):null,l=!!f;f=l&&"RD"==(new g.tQ(f.substr(0,2),f.substr(2))).type;var m=b instanceof g.rO?b.xa:null;c={title:b.title,author:b.author,author_and_views:e.shortViewCount?b.author+" \u2022 "+e.shortViewCount:b.author,aria_label:b.Dk||g.V("YTP_WATCH_VIDEO_OR_PLAYLIST",{TITLE:b.title},b.title),duration:k,url:b.Zk(c),is_live:m,
is_list:l,is_mix:f,background:d?"background-image: url("+d+")":""};b instanceof g.vQ&&(c.playlist_length=b.getLength());a.update(c)},f6=function(a,b){g.pH.call(this,{G:"div",
ca:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.o=a;this.created=!1},g6=function(a){g.W.call(this,{G:"div",
M:"ytp-upnext",P:{"aria-label":"{{aria_label}}"},J:[{G:"div",M:"ytp-cued-thumbnail-overlay-image",P:{style:"{{background}}"}},{G:"span",M:"ytp-upnext-top",J:[{G:"span",M:"ytp-upnext-header",J:["Up Next"]},{G:"span",M:"ytp-upnext-title",J:["{{title}}"]},{G:"span",M:"ytp-upnext-author",J:["{{author}}"]}]},{G:"a",M:"ytp-upnext-autoplay-icon",P:{role:"button",href:"{{url}}","aria-label":"Play next video"},J:[{G:"svg",P:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},J:[{G:"circle",M:"ytp-svg-autoplay-circle",
P:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{G:"circle",M:"ytp-svg-autoplay-ring",P:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{G:"path",M:"ytp-svg-fill",P:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{G:"span",M:"ytp-upnext-bottom",J:[{G:"span",M:"ytp-upnext-cancel"},{G:"span",M:"ytp-upnext-paused",J:["Autoplay is paused"]}]}]});var b=this.g["ytp-upnext-cancel"];
this.D=new g.W({G:"button",ca:["ytp-upnext-cancel-button","ytp-button"],P:{tabindex:"0","aria-label":"Cancel autoplay"},J:["Cancel"]});g.N(this,this.D);this.D.T("click",this.FP,this);this.D.sa(b);this.o=a;this.K=this.g["ytp-svg-autoplay-ring"];this.F=this.C=this.A=this.B=null;this.H=new g.Wt(this.gn,5E3,this);g.N(this,this.H);this.I=0;this.O(this.g["ytp-upnext-autoplay-icon"],"click",this.PR);this.wB();this.O(a,"autonavvisibility",this.wB);this.O(a,"mdxnowautoplaying",this.eR);this.O(a,"mdxautoplaycanceled",
this.fR);this.O(a,"mdxautoplayupnext",this.bE);3==this.o.Qa()&&(a=(a=g.dV(g.ZU(this.o)))?a.BI():null)&&this.bE(a)},sAa=function(a,b){a.B=b;
rAa(a,b,g.Y(a.o),"hqdefault.jpg")},h6=function(a,b){if(!a.A){g.UF("a11y-announce","Up Next "+a.B.title);
a.I=g.eG();a.A=new g.Wt((0,g.A)(a.rq,a,b),25);a.rq(b);var c=b||g.Y(a.o).experiments.l("autoplay_time")||1E4;a.o.ua("onAutonavCoundownStarted",c)}g.lq(a.element,"ytp-upnext-autoplay-paused")},j6=function(a){i6(a);
a.I=g.eG();a.rq();g.S(a.element,"ytp-upnext-autoplay-paused")},i6=function(a){a.A&&(a.A.dispose(),a.A=null)},k6=function(a,b){b=void 0===b?!1:b;
var c=g.Y(a.o);if(c.experiments.g("autonav_notifications")&&b&&window.Notification&&window.document.hasFocus){var d=window.Notification.permission;"default"==d?window.Notification.requestPermission():"granted"!=d||window.document.hasFocus()||(d=a.B.Yb(),a.gn(),a.C=new window.Notification("Up Next",{body:d.title,icon:d.bd(c)}),a.F=a.O(a.C,"click",a.FR),a.H.start())}i6(a);a.o.Uj(!1,b)},tAa=function(a){f6.call(this,a,"subscribecard-endscreen");
var b=a.getVideoData();this.A=new g.W({G:"div",M:"ytp-subscribe-card",J:[{G:"img",M:"ytp-author-image",P:{src:b.profilePicture}},{G:"div",M:"ytp-subscribe-card-right",J:[{G:"div",M:"ytp-author-name",J:[b.author]},{G:"div",M:"html5-subscribe-button-container"}]}]});g.N(this,this.A);this.A.sa(this.element);this.B=new g.I_("Subscribe",null,"Unsubscribe",null,!0,!1,b.Ih,b.subscribed,"trailer-endscreen",null,null,a);g.N(this,this.B);this.B.sa(this.A.g["html5-subscribe-button-container"]);this.hide()},
l6=function(a){var b=g.Y(a),c=g.vI||g.cf?{style:"will-change: opacity"}:void 0,d=b.g,e=["ytp-videowall-still"];
b.o&&e.push("ytp-videowall-show-text");g.W.call(this,{G:"a",ca:e,P:{href:"{{url}}",target:d?"_blank":"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},J:[{G:"div",M:"ytp-videowall-still-image",P:{style:"{{background}}"}},{G:"span",M:"ytp-videowall-still-info",J:[{G:"span",M:"ytp-videowall-still-info-bg",J:[{G:"span",M:"ytp-videowall-still-info-content",P:c,J:[{G:"span",M:"ytp-videowall-still-info-title",J:["{{title}}"]},{G:"span",
M:"ytp-videowall-still-info-author",J:["{{author_and_views}}"]},{G:"span",M:"ytp-videowall-still-info-live",J:["Live"]},{G:"span",M:"ytp-videowall-still-info-duration",J:["{{duration}}"]}]}]}]},{G:"span",ca:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],J:[{G:"span",M:"ytp-videowall-still-listlabel-icon"},"Playlist",{G:"span",M:"ytp-videowall-still-listlabel-length",J:[" (",{G:"span",J:["{{playlist_length}}"]},")"]}]},{G:"span",ca:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],
J:[{G:"span",M:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{G:"span",M:"ytp-videowall-still-listlabel-length",J:[" (50+)"]}]}]});this.C=d;this.o=a;this.A=null;this.B=new g.CF(this);g.N(this,this.B);this.T("click",this.F);this.T("keypress",this.H);this.B.O(a,"videodatachange",this.D);g.Y(a).X&&(a=a.app.ea,b=this.element,g.Oa(a.g,b),g.Ra(a.g,b),c=String(a.F++),b.setAttribute("data-visual-id",c),g.Ye(this,(0,g.A)(a.D,a,b)));this.D()},m6=function(a){f6.call(this,a,"videowall-endscreen");
this.L=a;this.F=0;this.B=[];this.H=this.D=this.C=null;this.I=this.R=!1;this.W=new g.CF(this);g.N(this,this.W);this.K=new g.Wt(g.Ea(g.S,this.element,"ytp-show-tiles"),0);g.N(this,this.K);var b=new g.W({G:"button",ca:["ytp-button","ytp-endscreen-previous"],P:{"aria-label":"Previous"},J:[g.QV()]});g.N(this,b);b.sa(this.element);b.T("click",this.AN,this);this.N=new g.jH({G:"div",M:"ytp-endscreen-content"});g.N(this,this.N);this.N.sa(this.element);b=new g.W({G:"button",ca:["ytp-button","ytp-endscreen-next"],
P:{"aria-label":"Next"},J:[g.RV()]});g.N(this,b);b.sa(this.element);b.T("click",this.zN,this);this.A=new g6(a);g.N(this,this.A);g.xV(this.o,this.A.element,4);this.hide()},n6=function(a){return g.yV(a.o)&&a.Iw()&&!a.H},uAa=function(a,b){return(0,g.I)(b.suggestions,function(b){b=g.FY(b);
g.N(a,b);return b})},o6=function(a){var b=a.Bt();
b!=a.R&&(a.R=b,a.o.U("autonavvisibility"))},p6=function(a){g.DV.call(this,a);
this.l=null;this.o=new g.CF(this);g.N(this,this.o);this.A=g.Y(a);vAa(a)?this.l=new m6(this.g):this.A.La?this.l=new tAa(this.g):this.l=new f6(this.g);g.N(this,this.l);g.xV(this.g,this.l.element,4);this.OC();this.o.O(a,"videodatachange",this.OC,this);this.o.O(a,"crn_endscreen",this.AL,this);this.o.O(a,"crx_endscreen",this.BL,this)},vAa=function(a){a=g.Y(a);
return a.hd&&!a.La};
g.t(f6,g.pH);f6.prototype.create=function(){this.created=!0};
f6.prototype.destroy=function(){this.created=!1};
f6.prototype.Iw=function(){return!1};
f6.prototype.Bt=function(){return!1};g.t(g6,g.W);g.h=g6.prototype;g.h.gn=function(){this.C&&(this.H.stop(),this.Ca(this.F),this.F=null,this.C.close(),this.C=null)};
g.h.wB=function(){g.oH(this,g.$U(this.o))};
g.h.FR=function(){window.focus();this.gn()};
g.h.hide=function(){g.W.prototype.hide.call(this)};
g.h.rq=function(a){a=a||g.Y(this.o).experiments.l("autoplay_time")||1E4;var b=Math.min(g.eG()-this.I,a);a=Math.min(b/a,1);this.K.setAttribute("stroke-dashoffset",-211*(a+1));1<=a&&3!=this.o.Qa()?k6(this,!0):this.A&&this.A.start()};
g.h.PR=function(a){!g.Od(this.D.element,g.qF(a))&&g.BX(a,this.o)&&k6(this)};
g.h.FP=function(){g.bV(this.o,!0)};
g.h.eR=function(a){this.o.Qa();this.show();h6(this,a)};
g.h.bE=function(a){this.o.Qa();this.B&&this.B.Yb().videoId==a.Yb().videoId||sAa(this,a)};
g.h.fR=function(){this.o.Qa();i6(this);this.hide()};
g.h.V=function(){i6(this);this.gn();g.W.prototype.V.call(this)};g.t(tAa,f6);g.t(l6,g.W);l6.prototype.kk=function(){g.BV(this.o,this.element);var a=this.A.Yb().videoId,b=this.A.getPlaylistId();g.O0(this.o.app,a,this.A.Ld,b,void 0,void 0,void 0)};
l6.prototype.F=function(a){g.BX(a,this.o,this.C,this.A.Ld||void 0)&&this.kk()};
l6.prototype.H=function(a){switch(a.keyCode){case 13:case 32:g.vF(a)||(this.kk(),g.uF(a))}};
l6.prototype.D=function(){var a=this.o.getVideoData(),b=g.Y(this.o);this.C=a.isDni?!1:b.g};g.t(m6,f6);g.h=m6.prototype;g.h.create=function(){f6.prototype.create.call(this);var a=this.o.getVideoData();a&&(this.C=uAa(this,a),this.D=a);this.Cg();this.W.O(this.o,"appresize",this.Cg);this.W.O(this.o,"onVideoAreaChange",this.Cg);this.W.O(this.o,"videodatachange",this.BN);this.W.O(this.o,"autonavchange",this.xA);this.W.O(this.o,"autonavcancel",this.yN);this.W.O(this.element,"transitionend",this.gT)};
g.h.destroy=function(){g.EF(this.W);g.$e(this.B);this.B=[];this.C=null;f6.prototype.destroy.call(this);g.lq(this.element,"ytp-show-tiles");this.K.stop()};
g.h.Iw=function(){return 1!=this.D.autonavState};
g.h.show=function(){f6.prototype.show.call(this);g.lq(this.element,"ytp-show-tiles");g.Y(this.o).o?g.Yt(this.K):this.K.start();(this.I||this.H&&this.H!=this.D.clientPlaybackNonce)&&g.bV(this.o,!1);n6(this)?(o6(this),2==this.D.autonavState?g.Y(this.o).experiments.g("fast_autonav_in_background")&&3==this.o.Ai()?k6(this.A,!0):h6(this.A):3==this.D.autonavState&&j6(this.A)):(g.bV(this.o,!0),o6(this))};
g.h.hide=function(){f6.prototype.hide.call(this);j6(this.A);o6(this)};
g.h.gT=function(a){g.qF(a)==this.element&&this.Cg()};
g.h.Cg=function(){if(this.C&&this.C.length){g.S(this.element,"ytp-endscreen-paginate");var a=g.pV(this.L,!0),b=g.CH(this.L);b&&(b=b.qd()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.C.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<k);){var q=b/2,r=e/2,v=b<=f-2&&n>=r*m,E=e<=k-2&&n>=q*m;if((q+1)/r*d/c>c/(q/(r+1)*d)&&E)n-=q*m,e+=2;else if(v)n-=r*m,b+=2;else if(E)n-=q*m,e+=2;else break}d=
!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m*=c;n*=c;m*=g.ad(a.width/m||1,1,1.21);n*=g.ad(a.height/n||1,1,1.21);m=Math.floor(Math.min(a.width,m));n=Math.floor(Math.min(a.height,n));a=this.N.element;g.Gh(a,m,n);g.nh(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});sAa(this.A,this.C[0]);g.T(this.element,"ytp-endscreen-takeover",n6(this));o6(this);m+=4;n+=4;for(f=c=0;f<b;f++)for(k=0;k<e;k++)if(q=c,r=0,d&&f>=b-2&&k>=e-2?r=1:0==k%2&&0==f%2&&(2>k&&
2>f?0==k&&0==f&&(r=2):r=2),q=g.bd(q+this.F,l),0!=r){v=this.B[c];v||(v=new l6(this.o),this.B[c]=v,a.appendChild(v.element));E=Math.floor(n*k/e);var H=Math.floor(m*f/b),L=Math.floor(n*(k+r)/e)-E-4,U=Math.floor(m*(f+r)/b)-H-4;g.uh(v.element,H,E);g.Gh(v.element,U,L);g.nh(v.element,"transitionDelay",(k+f)/20+"s");g.T(v.element,"ytp-videowall-still-mini",1==r);g.T(v.element,"ytp-videowall-still-large",2<r);r=v;q=this.C[q];r.A!=q&&(r.A=q,rAa(r,q,g.Y(r.o),g.jq(r.element,"ytp-videowall-still-large")?"hqdefault.jpg":
"mqdefault.jpg"),v=(q=q.Ld)&&q.itct)&&(q=r.o,g.Y(q).X&&(q=q.app.ea,r=r.element,E=r.getAttribute("data-visual-id"),g.Oa(q.g,r),g.zV(q,"onLogServerVeCreated",{id:E,tracking_params:v})));c++}g.T(this.element,"ytp-endscreen-paginate",c<l);for(b=this.B.length-1;b>=c;b--)e=this.B[b],g.Id(e.element),g.Ze(e);this.B.length=c}};
g.h.BN=function(){var a=this.o.getVideoData();this.D!=a&&(this.F=0,this.C=uAa(this,a),this.D=a,this.Cg())};
g.h.zN=function(){this.F+=this.B.length;this.Cg()};
g.h.AN=function(){this.F-=this.B.length;this.Cg()};
g.h.FK=function(){return!!this.A.A};
g.h.xA=function(a){1==a?(this.I=!1,this.H=this.D.clientPlaybackNonce,i6(this.A),this.l&&this.Cg()):(this.I=!0,this.l&&n6(this)&&(2==a?h6(this.A):3==a&&j6(this.A)))};
g.h.yN=function(a){if(a){for(a=0;a<this.B.length;a++)g.CV(this.L,this.B[a].element,!0);this.xA(1)}else this.H=null,this.I=!1;this.Cg()};
g.h.Bt=function(){return this.l&&n6(this)};g.t(p6,g.DV);g.h=p6.prototype;g.h.Yz=function(){var a=this.g.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!vAa(this.g)||b;a=g.OO(a,"ypc_module");var c=g.P0(this.g.app);return b&&!a&&!c};
g.h.Xz=function(){return this.l.Bt()};
g.h.BK=function(){return this.Xz()?this.l.FK():!1};
g.h.V=function(){g.vV(this.g,"endscreen");g.DV.prototype.V.call(this)};
g.h.load=function(){g.DV.prototype.load.call(this);this.l.show()};
g.h.unload=function(){g.DV.prototype.unload.call(this);this.l.hide();this.l.destroy()};
g.h.AL=function(a){this.Yz()&&(this.l.created||this.l.create(),"load"==a.getId()&&this.load())};
g.h.BL=function(a){"load"==a.getId()&&this.loaded&&this.unload()};
g.h.OC=function(){g.vV(this.g,"endscreen");var a=Math.max(1E3*(this.g.getVideoData().lengthSeconds-10),0);a=new g.qQ(a,0x8000000000000,{id:"preload",namespace:"endscreen"});g.N(this,a);var b=new g.qQ(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.N(this,b);g.sV(this.g,[a,b])};g.uY.endscreen=p6;})(_yt_player);
